# Generated by Django 6.0.5 on 2026-08-13 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='slug',
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='package_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Onboarding'), ('PROD_DEV', 'Product Development'), ('BUDGET_TECH', 'Budgeting & Technical'), ('FULL_COSTING', 'Full Project Costing'), ('BUSINESS_PLAN', 'Business Plan & Proposal')], default='STANDARD', max_length=50),
        ),
    ]
