# Generated by Django 6.0.5 on 2026-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_assessmentpackage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentpackage',
            name='company_name',
        ),
    ]
