# Generated by Django 6.0.5 on 2026-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentpackage',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for ad-hoc billing', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assessmentpackage',
            name='custom_title',
            field=models.CharField(blank=True, help_text="Custom charge name (e.g., 'Top Up for Product Development')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentpackage',
            name='package_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Onboarding'), ('PROD_DEV', 'Product Development'), ('BUDGET_TECH', 'Budgeting & Technical'), ('FULL_COSTING', 'Full Project Costing'), ('BUSINESS_PLAN', 'Business Plan & Proposal'), ('CUSTOM', 'Custom / Ad-Hoc Charge')], default='STANDARD', max_length=50),
        ),
    ]
