# Generated by Django 6.0.5 on 2026-08-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_assessmentpackage_custom_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='company_name',
            new_name='business_name',
        ),
    ]
