# Generated by Django 6.0.5 on 2026-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_company_name_payment_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text="Internal admin notes (e.g., 'Paid via Fidelity Bank Wire prior to platform launch')", null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Actual date payment occurred. Leave blank to use system created timestamp.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('HISTORICAL', 'Historical')], default='PAYSTACK', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the request was settled (backdate field for historical payments)', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('HISTORICAL', 'Historical')], default='PAYSTACK', max_length=30),
        ),
    ]
