# Generated by Django 6.0.5 on 2026-08-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_notes_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='PAYSTACK', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='PAYSTACK', max_length=30),
        ),
    ]
