# Generated by Django 6.0.5 on 2026-09-26 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0021_alter_availability_options_and_more'),
        ('payments', '0009_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FDAWorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('stage_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('full_activity_name', models.CharField(max_length=255)),
                ('short_stage_name', models.CharField(max_length=100)),
                ('assigned_role', models.CharField(choices=[('USER', 'Client'), ('AMBASSADOR', 'Associate'), ('ASSOCIATE_1', 'Associate 1'), ('ASSOCIATE_2', 'Associate 2'), ('ASSOCIATE_3', 'Associate 3'), ('ASSOCIATE_4', 'Associate 4'), ('ASSOCIATE_5', 'Associate 5'), ('CONSULTANT', 'Consultant'), ('SUPERVISOR', 'Supervisor'), ('SUPER_ADMIN', 'Super Admin')], default='ASSOCIATE_1', max_length=30)),
                ('default_payment_check', models.BooleanField(default=False, help_text='Requires payment gate check by default')),
            ],
            options={
                'verbose_name': 'FDA Workflow Stage',
                'verbose_name_plural': 'FDA Workflow Stages',
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='FDAProjectTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contacted', models.DateField(blank=True, null=True)),
                ('latest_update_blocker', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fda_tracker', to='dashboard.clientproject')),
            ],
        ),
        migrations.CreateModel(
            name='FDAPaymentGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('STAGE', 'Stage Level'), ('PROJECT', 'Project Level')], default='STAGE', max_length=10)),
                ('payment_required', models.BooleanField(default=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('TO_CONFIRM', 'To Confirm'), ('PENDING', 'Pending'), ('PART_PAID', 'Part Paid'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=20)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fda_gates', to='payments.paymentrequest')),
                ('verified_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fda_gates', to='payments.payment')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gates', to='fda.fdaprojecttracker')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fda.fdaworkflowstage')),
            ],
        ),
        migrations.CreateModel(
            name='FDAProjectStageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('ONGOING', 'Ongoing'), ('WAITING_INTERNAL', 'Waiting Internal'), ('WAITING_EXTERNAL', 'Waiting External'), ('DISCONTINUED', 'Discontinued'), ('ON_HOLD', 'On Hold'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler_override', models.ForeignKey(blank=True, help_text='Overrides default workflow role handler if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fda_activities', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_activities', to='fda.fdaprojecttracker')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fda.fdaworkflowstage')),
            ],
            options={
                'verbose_name_plural': 'FDA Project Stage Activities',
                'ordering': ['stage__stage_number'],
                'unique_together': {('tracker', 'stage')},
            },
        ),
    ]
