# Generated by Django 6.0.5 on 2026-05-27 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROFILE', 'Profile Update'), ('DOCUMENT', 'Document Upload'), ('PAYMENT', 'Payment Transaction'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('FDA_ACTIVE', 'FDA ACTIVE Clients'), ('PROD_DEV', 'Product Development Clients'), ('QMS_SETUP', 'Quality Systems Setup'), ('INTERNAL', 'INTERNAL')], default='FDA_ACTIVE', max_length=20)),
                ('client_package', models.CharField(choices=[('PRODUCT_REG', 'Product Registration Support'), ('FACILITY_REG', 'Facility Registration Support'), ('COMPLETE', 'FDA Complete Registration Support'), ('PROD_DEV', 'Product Development'), ('QMS_TRAIN', 'QMS Setup and Training'), ('QUERY_RESP', 'FDA Query Response Support'), ('PROD_RENEW', 'Product Registration Renewal'), ('FAC_RENEW', 'Facility Registration Renewal'), ('AD_REG', 'Ad Registration Support'), ('OTHERS', 'Others')], max_length=20)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('COSMETICS', 'Cosmetics'), ('PHARMA', 'Pharmaceuticals'), ('FABRICS', 'Fabrics'), ('NON_FOOD', 'Non Food'), ('SUPPLEMENTS', 'Supplements'), ('OTHERS', 'Others')], max_length=20)),
                ('region', models.CharField(choices=[('AHAFO', 'Ahafo'), ('ASHANTI', 'Ashanti'), ('BONO', 'Bono'), ('BONO_EAST', 'Bono East'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('GREATER_ACCRA', 'Greater Accra'), ('NORTH_EAST', 'North East'), ('NORTHERN', 'Northern'), ('OTI', 'Oti'), ('SAVANNAH', 'Savannah'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('VOLTA', 'Volta'), ('WESTERN', 'Western'), ('WESTERN_NORTH', 'Western North'), ('DIASPORA', 'Diaspora')], max_length=20)),
                ('project_start_date', models.DateField()),
                ('product_names', models.TextField(blank=True, help_text='List of products (e.g. Elite Cereal Mix).', null=True)),
                ('overall_project_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_consultant', models.ForeignKey(blank=True, help_text="Consultant handling this client's operational workflow.", limit_choices_to={'role': 'CONSULTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='The client this project belongs to.', limit_choices_to={'role': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PAID_PART', 'Paid Part'), ('AWAITING', 'Awaiting Payment'), ('NOT_PAID', 'Not Paid'), ('TBD', 'TBD'), ('NA', 'N/A'), ('PENDING', 'Pending')], default='NOT_PAID', max_length=20)),
                ('activity_status', models.CharField(choices=[('PAUSED', 'Paused'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('NOT_STARTED', 'Not Started'), ('CLIENT_TASK', 'Client Task'), ('PENDING', 'Pending')], default='NOT_STARTED', max_length=20)),
                ('activity_notes', models.TextField(blank=True, null=True)),
                ('activity_deadline', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.clientproject')),
            ],
            options={
                'verbose_name_plural': 'Project Activities',
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BUSINESS_CERT', 'Business Registration Certificate'), ('HEALTH_CARD', 'Medical Fitness Certificates (Health Cards)'), ('FACILITY_SKETCH', 'Facility Floor Sketch Plan'), ('PRODUCT_LABEL', 'Proposed Product Labels'), ('WATER_ANALYSIS', 'Water Analysis Report (If Applicable)'), ('PEST_CONTROL', 'Pest Control Contract/Certificate'), ('SOP_MANUAL', 'Standard Operating Procedures (SOPs)'), ('SUPPLEMENTARY_DOC', 'Supplementary Documents')], max_length=50)),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='client_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected / Needs Resubmission')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_type', 'SUPPLEMENTARY_DOC'), _negated=True), fields=('client', 'document_type'), name='unique_core_document_per_client'), models.UniqueConstraint(condition=models.Q(('document_type', 'SUPPLEMENTARY_DOC')), fields=('client', 'document_type', 'custom_title'), name='unique_supplementary_document_title_per_client')],
            },
        ),
    ]
