# Generated by Django 5.0.7 on 2026-07-04 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activitynote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Tracks the explicit actor (Client vs. Ambassador proxy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AmbassadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(help_text='Critical for in-person visual client verification.', upload_to='ambassadors/avatars/')),
                ('bio', models.TextField(blank=True)),
                ('is_active_field_agent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('REMOTE', 'Remote Assistance'), ('IN_PERSON', 'In-Person Field Visit')], default='REMOTE', max_length=10)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned / In Progress'), ('COMPLETED', 'Fully Resolved'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=15)),
                ('client_marked_complete', models.BooleanField(default=False)),
                ('client_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ambassador_marked_complete', models.BooleanField(default=False)),
                ('ambassador_completed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ambassadors', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.clientproject')),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.ambassadorprofile')),
            ],
        ),
    ]
