# Generated by Django 6.0.5 on 2026-07-08 23:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_clientdocument_uploaded_by_ambassadorprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorprofile',
            name='id_card',
            field=models.ImageField(default=django.utils.timezone.now, help_text="Upload a valid Government Issued National ID Card, Passport, or Driver's License.", upload_to='ambassadors/ids/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambassadorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ambassadorprofile',
            name='verification_selfie',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Live clear selfie photo matching your ID Card profile snapshot.', upload_to='ambassadors/selfies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambassadorprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambassadorprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Critical for in-person visual client verification.', upload_to='ambassadors/avatars/'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Tracks the explicit actor (Client vs. Ambassador).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded_by_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
