# Generated by Django 6.0.5 on 2026-07-09 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ambassadorprofile_id_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Needed for visual verification.', upload_to='consultants/avatars/')),
                ('bio', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='consultant_docs/%Y/%m/')),
                ('id_card', models.ImageField(help_text="Upload a valid Government Issued National ID Card, Passport, or Driver's License.", upload_to='consultants/ids/')),
                ('verification_selfie', models.ImageField(help_text='Live clear selfie photo matching your ID Card profile snapshot.', upload_to='consultants/selfies/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('is_active_consultant', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
