# Generated by Django 6.0.5 on 2026-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_consultantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='cv',
            field=models.FileField(help_text='Upload your CV.', upload_to='consultant_docs/%Y/%m/'),
        ),
    ]
