# Generated by Django 6.0.5 on 2026-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_consultantprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('BUSINESS_CERT', 'Business Registration Certificate'), ('FACILITY_SKETCH', 'Facility Floor Sketch Plan'), ('COMPANY_LOGO', 'Company Logo'), ('BRAND_LOGO', 'Brand Logo'), ('PRODUCT_LABEL', 'Proposed Product Labels'), ('WATER_ANALYSIS', 'Water Analysis Report'), ('HEALTH_CARD', 'Medical Fitness Certificate'), ('PEST_CONTROL', 'Pest Control Contract/Certificate'), ('SOP_MANUAL', 'Standard Operating Procedures (SOPs)'), ('MENU', 'Menu'), ('SUPPLEMENTARY_DOC', 'Supplementary Documents')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('FOOD_SERVICE', 'Food Service'), ('COSMETICS', 'Cosmetics'), ('PHARMA', 'Pharmaceuticals'), ('FABRICS', 'Fabrics'), ('NON_FOOD', 'Non Food'), ('SUPPLEMENTS', 'Supplements'), ('OTHERS', 'Others')], max_length=20),
        ),
    ]
