# Generated by Django 6.0.5 on 2026-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_clientdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('BUSINESS_CERT', 'Business Registration Certificate'), ('FACILITY_SKETCH', 'Facility Floor Sketch Plan'), ('COMPANY_LOGO', 'Company Logo'), ('BRAND_LOGO', 'Brand Logo'), ('PRODUCT_LABEL', 'Proposed Product Labels'), ('HEALTH_CARD', 'Medical Fitness Certificate'), ('WATER_ANALYSIS', 'Water Analysis Report'), ('MENU', 'Menu'), ('PEST_CONTROL', 'Pest Control Contract/Certificate'), ('SOP_MANUAL', 'Standard Operating Procedures (SOPs)'), ('SUPPLEMENTARY_DOC', 'Supplementary Documents')], max_length=50),
        ),
    ]
