# Generated by Django 6.0.5 on 2026-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_clientdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='client_docs/%Y/%m/'),
        ),
    ]
