# Generated by Django 6.0.5 on 2026-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_clientdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('FOOD_SERVICE', 'Food Service'), ('COSMETICS', 'Cosmetics'), ('PHARMA', 'Pharmaceuticals'), ('FABRICS', 'Fabrics'), ('NON_FOOD', 'Non Food'), ('SUPPLEMENTS', 'Supplements'), ('HERBAL', 'Herbal'), ('HOUSEHOLD_CHEMICAL', 'Household Chemicals'), ('OTHERS', 'Others')], max_length=20),
        ),
    ]
