# Generated by Django 6.0.5 on 2026-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_clientproject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('BUSINESS_CERT', 'Business Registration Certificate'), ('FACILITY_SKETCH', 'Facility Floor Sketch Plan'), ('COMPANY_LOGO', 'Company Logo'), ('BRAND_LOGO', 'Product/Brand Logo'), ('PRODUCT_LABEL', 'Proposed Product Labels'), ('PRODUCT_PICS', 'Pictures of Product (With Label)'), ('LAB_RESULTS', 'Laboratory Results'), ('HEALTH_CARD', 'Medical Fitness Certificate'), ('WATER_ANALYSIS', 'Water Analysis Report'), ('MENU', 'Menu'), ('RECIPE_STEPS', 'Recipe Steps'), ('PEST_CONTROL', 'Pest Control Contract/Certificate'), ('SOP_MANUAL', 'Standard Operating Procedures (SOPs)'), ('SUPPLEMENTARY_DOC', 'Supplementary Documents')], max_length=50),
        ),
    ]
