# Generated by Django 6.0.5 on 2026-07-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorassignment',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.ambassadorprofile'),
        ),
    ]
