# Generated by Django 6.0.5 on 2026-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_ambassadorassignment_ambassador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorassignment',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned / In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=15),
        ),
    ]
