# Generated by Django 6.0.5 on 2026-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_ambassadorassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorassignment',
            name='modality',
            field=models.CharField(choices=[('REMOTE', 'Remote Assistance'), ('IN_PERSON', 'In-Person Visit')], default='REMOTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='ambassadorassignment',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned/In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UNASSIGNED', max_length=15),
        ),
    ]
