# Generated by Django 6.0.5 on 2026-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_ambassadorassignment_modality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
