# Generated by Django 6.0.5 on 2026-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_ambassadorassignment_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
