# Generated by Django 6.0.5 on 2026-09-07 22:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_consultantassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['week_start_date', 'weekday', 'start_time']},
        ),
        migrations.AddField(
            model_name='availability',
            name='week_start_date',
            field=models.DateField(default=dashboard.models.get_current_monday),
        ),
    ]
