# Generated by Django 6.0.5 on 2026-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Registered business name (Applicable to clients/users).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Primary contact number for updates.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUPERVISOR', 'Supervisor'), ('CONSULTANT', 'Consultant'), ('AMBASSADOR', 'Ambassador'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
