# Generated by Django 6.0.5 on 2026-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_number',
            field=models.CharField(blank=True, help_text='Secondary contact number for updates.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('AHAFO', 'Ahafo'), ('ASHANTI', 'Ashanti'), ('BONO', 'Bono'), ('BONO_EAST', 'Bono East'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('GREATER_ACCRA', 'Greater Accra'), ('NORTH_EAST', 'North East'), ('NORTHERN', 'Northern'), ('OTI', 'Oti'), ('SAVANNAH', 'Savannah'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('VOLTA', 'Volta'), ('WESTERN', 'Western'), ('WESTERN_NORTH', 'Western North'), ('DIASPORA', 'Diaspora')], default='AHAFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
