# Generated by Django 6.0.5 on 2026-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_alternative_number_user_region_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUPERVISOR', 'Supervisor'), ('CONSULTANT', 'Consultant'), ('AMBASSADOR', 'Ambassador'), ('SHEPAG', 'Shepag'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
