# Generated by Django 6.0.5 on 2026-07-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUPERVISOR', 'Supervisor'), ('CONSULTANT', 'Consultant'), ('ASSOCIATE', 'Associate'), ('SHEPAG', 'Shepag'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
