# Generated by Django 6.0.5 on 2026-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('AMBASSADOR', 'Associate'), ('CONSULTANT', 'Consultant'), ('SUPERVISOR', 'Supervisor'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
        ),
    ]
