# Generated by Django 6.0.5 on 2026-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(choices=[('FOOD', 'Food'), ('FOOD_SERVICE', 'Food Service'), ('COSMETICS', 'Cosmetics'), ('PHARMA', 'Pharmaceuticals'), ('FABRICS', 'Fabrics'), ('NON_FOOD', 'Non Food'), ('SUPPLEMENTS', 'Supplements'), ('OTHERS', 'Others')], default='FOOD', max_length=30),
        ),
    ]
