# Generated by Django 6.0.5 on 2026-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(choices=[('FOOD', 'Food'), ('FOOD_SERVICE', 'Food Service'), ('COSMETICS', 'Cosmetics'), ('PHARMA', 'Pharmaceuticals'), ('FABRICS', 'Fabrics'), ('NON_FOOD', 'Non Food'), ('SUPPLEMENTS', 'Supplements'), ('HERBAL', 'Herbal'), ('HOUSEHOLD_CHEMICAL', 'Household Chemicals'), ('OTHERS', 'Others')], default='FOOD', max_length=30),
        ),
    ]
