# Generated by Django 6.0.5 on 2026-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number in case of emergencies.', max_length=20, null=True),
        ),
    ]
