# Generated by Django 6.0.5 on 2026-08-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
