# Generated by Django 6.0.5 on 2026-08-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Client'), ('AMBASSADOR', 'Associate'), ('CONSULTANT', 'Consultant'), ('SUPERVISOR', 'Supervisor'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
        ),
    ]
