# Generated by Django 6.0.5 on 2026-08-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='Not Set', max_length=255),
        ),
    ]
