# Generated by Django 6.0.5 on 2026-09-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Client'), ('AMBASSADOR', 'Associate'), ('ASSOCIATE_1', 'Associate 1'), ('ASSOCIATE_2', 'Associate 2'), ('ASSOCIATE_3', 'Associate 3'), ('ASSOCIATE_4', 'Associate 4'), ('ASSOCIATE_5', 'Associate 5'), ('CONSULTANT', 'Consultant'), ('SUPERVISOR', 'Supervisor'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
        ),
    ]
