# Generated by Django 6.0.5 on 2026-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COMPANY_KNOWLEDGE', 'PFS Company Knowledge'), ('SERVICES', 'PFS Services'), ('CLIENT_MANAGEMENT', 'Client Management'), ('COMMUNICATION', 'Communication'), ('PROFESSIONALISM', 'Professionalism'), ('PRODUCT_DEVELOPMENT', 'Product Development'), ('FDA', 'FDA'), ('GMP', 'GMP'), ('SALES', 'Sales'), ('CULTURE', 'PFS Culture')], max_length=50)),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
