# Generated by Django 6.0.5 on 2026-08-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_exam_examattempt_exam_question_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
