# Generated by Django 6.0.5 on 2026-08-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_exam_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='examinations.exam'),
        ),
    ]
