# Generated by Django 6.0.5 on 2026-08-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0007_examattempt_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If locked, associates cannot take or view this examination.'),
        ),
    ]
